package throw_Exception;
import java.util.Scanner;//scanner packages....
public class Age2 {
        int age;//decalred variable
	static Scanner sc = new Scanner(System.in);	
	public static void main(String[] args) {// create main method.....
	Age2 obj=new Age2();//create object the same class.....
	obj.aceept();//call the accept method......
	}
	public void aceept() {
			//accept the detail of age from user
			System.out.print("Enter your Age : ");
			 age = sc.nextInt();
			try {//use try block where exception is show
				if(age < 18 )//use if condition......
				{
					throw new User_define_exception2("Invalid Age.");//use the user defined exception......
				}
				else
				{
					System.out.println("You are valid "+age);
				}
			}
			catch(Exception e)//use catch block for handle the exception.......
			{
				System.out.println(e);
			}
			
				
		

	}
}
